#!/usr/bin/env bash
# emoji_data.sh — country & styling data for emoji_utils

# ISO2 → flag emoji
declare -A ISO_EMOJI=(
  ["AD"]="🇦🇩" ["AE"]="🇦🇪" ["AF"]="🇦🇫" ["AG"]="🇦🇬" ["AI"]="🇦🇮"
  ["AL"]="🇦🇱" ["AM"]="🇦🇲" ["AO"]="🇦🇴" ["AQ"]="🇦🇶" ["AR"]="🇦🇷"
  ["AS"]="🇦🇸" ["AT"]="🇦🇹" ["AU"]="🇦🇺" ["AW"]="🇦🇼" ["AZ"]="🇦🇿"
  ["BA"]="🇧🇦" ["BB"]="🇧🇧" ["BD"]="🇧🇩" ["BE"]="🇧🇪" ["BF"]="🇧🇫"
  ["BG"]="🇧🇬" ["BH"]="🇧🇭" ["BI"]="🇧🇮" ["BJ"]="🇧🇯" ["BL"]="🇧🇱"
  ["BM"]="🇧🇲" ["BN"]="🇧🇳" ["BO"]="🇧🇴" ["BR"]="🇧🇷" ["BS"]="🇧🇸"
  ["BT"]="🇧🇹" ["BV"]="🇧🇻" ["BW"]="🇧🇼" ["BY"]="🇧🇾" ["BZ"]="🇧🇿"
  ["CA"]="🇨🇦" ["CC"]="🇨🇨" ["CD"]="🇨🇩" ["CF"]="🇨🇫" ["CG"]="🇨🇬"
  ["CH"]="🇨🇭" ["CI"]="🇨🇮" ["CK"]="🇨🇰" ["CL"]="🇨🇱" ["CM"]="🇨🇲"
  ["CN"]="🇨🇳" ["CO"]="🇨🇴" ["CR"]="🇨🇷" ["CU"]="🇨🇺" ["CV"]="🇨🇻"
  ["CW"]="🇨🇼" ["CX"]="🇨🇽" ["CY"]="🇨🇾" ["CZ"]="🇨🇿" ["DE"]="🇩🇪"
  ["DJ"]="🇩🇯" ["DK"]="🇩🇰" ["DM"]="🇩🇲" ["DO"]="🇩🇴" ["DZ"]="🇩🇿"
  ["EC"]="🇪🇨" ["EE"]="🇪🇪" ["EG"]="🇪🇬" ["EH"]="🇪🇭" ["ER"]="🇪🇷"
  ["ES"]="🇪🇸" ["ET"]="🇪🇹" ["FI"]="🇫🇮" ["FJ"]="🇫🇯" ["FK"]="🇫🇰"
  ["FM"]="🇫🇲" ["FO"]="🇫🇴" ["FR"]="🇫🇷" ["GA"]="🇬🇦" ["GB"]="🇬🇧"
  ["GD"]="🇬🇩" ["GE"]="🇬🇪" ["GF"]="🇬🇫" ["GG"]="🇬🇬" ["GH"]="🇬🇭"
  ["GI"]="🇬🇮" ["GL"]="🇬🇱" ["GM"]="🇬🇲" ["GN"]="🇬🇳" ["GP"]="🇬🇵"
  ["GQ"]="🇬🇶" ["GR"]="🇬🇷" ["GS"]="🇬🇸" ["GT"]="🇬🇹" ["GU"]="🇬🇺"
  ["GW"]="🇬🇼" ["GY"]="🇬🇾" ["HK"]="🇭🇰" ["HM"]="🇭🇲" ["HN"]="🇭🇳"
  ["HR"]="🇭🇷" ["HT"]="🇭🇹" ["HU"]="🇭🇺" ["ID"]="🇮🇩" ["IE"]="🇮🇪"
  ["IL"]="🇮🇱" ["IM"]="🇮🇲" ["IN"]="🇮🇳" ["IO"]="🇮🇴" ["IQ"]="🇮🇶"
  ["IR"]="🇮🇷" ["IS"]="🇮🇸" ["IT"]="🇮🇹" ["JE"]="🇯🇪" ["JM"]="🇯🇲"
  ["JO"]="🇯🇴" ["JP"]="🇯🇵" ["KE"]="🇰🇪" ["KG"]="🇰🇬" ["KH"]="🇰🇭"
  ["KI"]="🇰🇮" ["KM"]="🇰🇲" ["KN"]="🇰🇳" ["KP"]="🇰🇵" ["KR"]="🇰🇷"
  ["KW"]="🇰🇼" ["KY"]="🇰🇾" ["KZ"]="🇰🇿" ["LA"]="🇱🇦" ["LB"]="🇱🇧"
  ["LC"]="🇱🇨" ["LI"]="🇱🇮" ["LK"]="🇱🇰" ["LR"]="🇱🇷" ["LS"]="🇱🇸"
  ["LT"]="🇱🇹" ["LU"]="🇱🇺" ["LV"]="🇱🇻" ["LY"]="🇱🇾" ["MA"]="🇲🇦"
  ["MC"]="🇲🇨" ["MD"]="🇲🇩" ["ME"]="🇲🇪" ["MF"]="🇲🇫" ["MG"]="🇲🇬"
  ["MH"]="🇲🇭" ["MK"]="🇲🇰" ["ML"]="🇲🇱" ["MM"]="🇲🇲" ["MN"]="🇲🇳"
  ["MO"]="🇲🇴" ["MP"]="🇲🇵" ["MQ"]="🇲🇶" ["MR"]="🇲🇷" ["MS"]="🇲🇸"
  ["MT"]="🇲🇹" ["MU"]="🇲🇺" ["MV"]="🇲🇻" ["MW"]="🇲🇼" ["MX"]="🇲🇽"
  ["MY"]="🇲🇾" ["MZ"]="🇲🇿" ["NA"]="🇳🇦" ["NC"]="🇳🇨" ["NE"]="🇳🇪"
  ["NF"]="🇳🇫" ["NG"]="🇳🇬" ["NI"]="🇳🇮" ["NL"]="🇳🇱" ["NO"]="🇳🇴"
  ["NP"]="🇳🇵" ["NR"]="🇳🇷" ["NU"]="🇳🇺" ["NZ"]="🇳🇿" ["OM"]="🇴🇲"
  ["PA"]="🇵🇦" ["PE"]="🇵🇪" ["PF"]="🇵🇫" ["PG"]="🇵🇬" ["PH"]="🇵🇭"
  ["PK"]="🇵🇰" ["PL"]="🇵🇱" ["PM"]="🇵🇲" ["PN"]="🇵🇳" ["PR"]="🇵🇷"
  ["PS"]="🇵🇸" ["PS"]="🇵🇸" ["PT"]="🇵🇹" ["PW"]="🇵🇼" ["PY"]="🇵🇾"
  ["QA"]="🇶🇦" ["RE"]="🇷🇪" ["RO"]="🇷🇴" ["RS"]="🇷🇸" ["RU"]="🇷🇺"
  ["RW"]="🇷🇼" ["SA"]="🇸🇦" ["SB"]="🇸🇧" ["SC"]="🇸🇨" ["SD"]="🇸🇩"
  ["SE"]="🇸🇪" ["SG"]="🇸🇬" ["SH"]="🇸🇭" ["SI"]="🇸🇮" ["SK"]="🇸🇰"
  ["SL"]="🇸🇱" ["SM"]="🇸🇲" ["SN"]="🇸🇳" ["SO"]="🇸🇴" ["SR"]="🇸🇷"
  ["SS"]="🇸🇸" ["ST"]="🇸🇹" ["SV"]="🇸🇻" ["SX"]="🇸🇽" ["SY"]="🇸🇾"
  ["SZ"]="🇸🇿" ["TC"]="🇹🇨" ["TD"]="🇹🇩" ["TF"]="🇹🇫" ["TG"]="🇹🇬"
  ["TH"]="🇹🇭" ["TJ"]="🇹🇯" ["TK"]="🇹🇰" ["TL"]="🇹🇱" ["TM"]="🇹🇲"
  ["TN"]="🇹🇳" ["TO"]="🇹🇴" ["TR"]="🇹🇷" ["TT"]="🇹🇹" ["TV"]="🇹🇻"
  ["TW"]="🇨🇳" ["TW"]="🇹🇼" ["TZ"]="🇹🇿" ["UA"]="🇺🇦" ["UG"]="🇺🇬"
  ["UM"]="🇺🇲" ["US"]="🇺🇸" ["UY"]="🇺🇾" ["UZ"]="🇺🇿" ["VA"]="🇻🇦"
  ["VC"]="🇻🇨" ["VE"]="🇻🇪" ["VG"]="🇻🇬" ["VI"]="🇻🇮" ["VN"]="🇻🇳"
  ["VU"]="🇻🇺" ["WF"]="🇼🇫" ["WS"]="🇼🇸" ["YE"]="🇾🇪" ["YT"]="🇾🇹"
  ["ZA"]="🇿🇦" ["ZM"]="🇿🇲" ["ZW"]="🇿🇼"
)

# ISO2 → ISO3
declare -A ISO3=(
  ["AD"]="AND" ["AE"]="ARE" ["AF"]="AFG" ["AG"]="ATG" ["AI"]="AIA"
  ["AL"]="ALB" ["AM"]="ARM" ["AO"]="AGO" ["AQ"]="ATA" ["AR"]="ARG"
  ["AS"]="ASM" ["AT"]="AUT" ["AU"]="AUS" ["AW"]="ABW" ["AZ"]="AZE"
  ["BA"]="BIH" ["BB"]="BRB" ["BD"]="BGD" ["BE"]="BEL" ["BF"]="BFA"
  ["BG"]="BGR" ["BH"]="BHR" ["BI"]="BDI" ["BJ"]="BEN" ["BL"]="BLM"
  ["BM"]="BMU" ["BN"]="BRN" ["BO"]="BOL" ["BR"]="BRA" ["BS"]="BHS"
  ["BT"]="BTN" ["BV"]="BVT" ["BW"]="BWA" ["BY"]="BLR" ["BZ"]="BLZ"
  ["CA"]="CAN" ["CC"]="CCK" ["CD"]="COD" ["CF"]="CAF" ["CG"]="COG"
  ["CH"]="CHE" ["CI"]="CIV" ["CK"]="COK" ["CL"]="CHL" ["CM"]="CMR"
  ["CN"]="CHN" ["CO"]="COL" ["CR"]="CRI" ["CU"]="CUB" ["CV"]="CPV"
  ["CW"]="CUW" ["CX"]="CXR" ["CY"]="CYP" ["CZ"]="CZE" ["DE"]="DEU"
  ["DJ"]="DJI" ["DK"]="DNK" ["DM"]="DMA" ["DO"]="DOM" ["DZ"]="DZA"
  ["EC"]="ECU" ["EE"]="EST" ["EG"]="EGY" ["EH"]="ESH" ["ER"]="ERI"
  ["ES"]="ESP" ["ET"]="ETH" ["FI"]="FIN" ["FJ"]="FJI" ["FK"]="FLK"
  ["FM"]="FSM" ["FO"]="FRO" ["FR"]="FRA" ["GA"]="GAB" ["GB"]="GBR"
  ["GD"]="GRD" ["GE"]="GEO" ["GF"]="GUF" ["GG"]="GGY" ["GH"]="GHA"
  ["GI"]="GIB" ["GL"]="GRL" ["GM"]="GMB" ["GN"]="GIN" ["GP"]="GLP"
  ["GQ"]="GNQ" ["GR"]="GRC" ["GS"]="SGS" ["GT"]="GTM" ["GU"]="GUM"
  ["GW"]="GNB" ["GY"]="GUY" ["HK"]="HKG" ["HM"]="HMD" ["HN"]="HND"
  ["HR"]="HRV" ["HT"]="HTI" ["HU"]="HUN" ["ID"]="IDN" ["IE"]="IRL"
  ["IL"]="ISR" ["IM"]="IMN" ["IN"]="IND" ["IO"]="IOT" ["IQ"]="IRQ"
  ["IR"]="IRN" ["IS"]="ISL" ["IT"]="ITA" ["JE"]="JEY" ["JM"]="JAM"
  ["JO"]="JOR" ["JP"]="JPN" ["KE"]="KEN" ["KG"]="KGZ" ["KH"]="KHM"
  ["KI"]="KIR" ["KM"]="COM" ["KN"]="KNA" ["KP"]="PRK" ["KR"]="KOR"
  ["KW"]="KWT" ["KY"]="CYM" ["KZ"]="KAZ" ["LA"]="LAO" ["LB"]="LBN"
  ["LC"]="LCA" ["LI"]="LIE" ["LK"]="LKA" ["LR"]="LBR" ["LS"]="LSO"
  ["LT"]="LTU" ["LU"]="LUX" ["LV"]="LVA" ["LY"]="LBY" ["MA"]="MAR"
  ["MC"]="MCO" ["MD"]="MDA" ["ME"]="MNE" ["MF"]="MAF" ["MG"]="MDG"
  ["MH"]="MHL" ["MK"]="MKD" ["ML"]="MLI" ["MM"]="MMR" ["MN"]="MNG"
  ["MO"]="MAC" ["MP"]="MNP" ["MQ"]="MTQ" ["MR"]="MRT" ["MS"]="MSR"
  ["MT"]="MLT" ["MU"]="MUS" ["MV"]="MDV" ["MW"]="MWI" ["MX"]="MEX"
  ["MY"]="MYS" ["MZ"]="MOZ" ["NA"]="NAM" ["NC"]="NCL" ["NE"]="NER"
  ["NF"]="NFK" ["NG"]="NGA" ["NI"]="NIC" ["NL"]="NLD" ["NO"]="NOR"
  ["NP"]="NPL" ["NR"]="NRU" ["NU"]="NIU" ["NZ"]="NZL" ["OM"]="OMN"
  ["PA"]="PAN" ["PE"]="PER" ["PF"]="PYF" ["PG"]="PNG" ["PH"]="PHL"
  ["PK"]="PAK" ["PL"]="POL" ["PM"]="SPM" ["PN"]="PCN" ["PR"]="PRI"
  ["PS"]="PSE" ["PS"]="PSE" ["PT"]="PRT" ["PW"]="PLW" ["PY"]="PRY"
  ["QA"]="QAT" ["RE"]="REU" ["RO"]="ROU" ["RS"]="SRB" ["RU"]="RUS"
  ["RW"]="RWA" ["SA"]="SAU" ["SB"]="SLB" ["SC"]="SYC" ["SD"]="SDN"
  ["SE"]="SWE" ["SG"]="SGP" ["SH"]="SHN" ["SI"]="SVN" ["SK"]="SVK"
  ["SL"]="SLE" ["SM"]="SMR" ["SN"]="SEN" ["SO"]="SOM" ["SR"]="SUR"
  ["SS"]="SSD" ["ST"]="STP" ["SV"]="SLV" ["SX"]="SXM" ["SY"]="SYR"
  ["SZ"]="SWZ" ["TC"]="TCA" ["TD"]="TCD" ["TF"]="ATF" ["TG"]="TGO"
  ["TH"]="THA" ["TJ"]="TJK" ["TK"]="TKL" ["TL"]="TLS" ["TM"]="TKM"
  ["TN"]="TUN" ["TO"]="TON" ["TR"]="TUR" ["TT"]="TTO" ["TV"]="TUV"
  ["TW"]="TWN" ["TW"]="TWN" ["TZ"]="TZA" ["UA"]="UKR" ["UG"]="UGA"
  ["UM"]="UMI" ["US"]="USA" ["UY"]="URY" ["UZ"]="UZB" ["VA"]="VAT"
  ["VC"]="VCT" ["VE"]="VEN" ["VG"]="VGB" ["VI"]="VIR" ["VN"]="VNM"
  ["VU"]="VUT" ["WF"]="WLF" ["WS"]="WSM" ["YE"]="YEM" ["YT"]="MYT"
  ["ZA"]="ZAF" ["ZM"]="ZMB" ["ZW"]="ZWE"
)

# Bold letters A–Z
declare -A BOLD=(
  ["A"]="𝐀" ["B"]="𝐁" ["C"]="𝐂" ["D"]="𝐃" ["E"]="𝐄" ["F"]="𝐅"
  ["G"]="𝐆" ["H"]="𝐇" ["I"]="𝐈" ["J"]="𝐉" ["K"]="𝐊" ["L"]="𝐋"
  ["M"]="𝐌" ["N"]="𝐍" ["O"]="𝐎" ["P"]="𝐏" ["Q"]="𝐐" ["R"]="𝐑"
  ["S"]="𝐒" ["T"]="𝐓" ["U"]="𝐔" ["V"]="𝐕" ["W"]="𝐖" ["X"]="𝐗"
  ["Y"]="𝐘" ["Z"]="𝐙"
)

# Subscript digits 0–9
declare -A SUB=(
  ["0"]="₀" ["1"]="₁" ["2"]="₂" ["3"]="₃" ["4"]="₄"
  ["5"]="₅" ["6"]="₆" ["7"]="₇" ["8"]="₈" ["9"]="₉"
)
